version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_PASS=password"
      - "RABBITMQ_DEFAULT_USER=username"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
